language: node_js
node_js:
 - 6.1
 - 6.0
 - 5.11
 - 5.10
 - 5.9
 - 5.8
 - 5.7
 - 5.6
 - 5.5
 - 5.4
 - 5.3
 - 5.2
 - 5.1
 - 5.0
 - 4.4
 - 4.3
 - 4.2
 - 4.1
 - 4.0

install:
    npm install --global mocha

script:
  - export NS_HOST=$NS_HOST
  - export NS_KEYNAME=$NS_KEYNAME
  - export NS_KEY=$NS_KEY
  - export NS_CPCODE=$NS_CPCODE
  - npm install
  - mocha --no-timeouts test/test-netstorage.js
