language: node_js
node_js:
 - 6.1
 - 6.0
 - 5.11
 - 5.10
 - 5.9
 - 5.8
 - 5.7
 - 5.6
 - 5.5
 - 5.4
 - 5.3
 - 5.2
 - 5.1
 - 5.0
 - 4.4
 - 4.3
 - 4.2
 - 4.1
 - 4.0

env:
  global:
    - secure: hIjLJ/GFOC4XWTu4pAcrnaSsbLeDO4/4CpYPxqaTwx9RBVySVp2Um1BaNRrL3NMyEbxp2wWRltffslD1O1jtit7vc84VIjugo9ngcb/GXuWubGFML8XLMVYYyf/SZNNUNdEnkxzm0Zo1a4s9JDBaqtFPS+jUDimjA+jroWuddTN+QBX2iTTvHwoPsR6zUUqrqAChXIhnigE+WPTK4rKPQtgVaw4wgG7ieqZYP8pzjF7cQVS1JZzvSe+Pu0ONDodxyp8ZAuRpSxS7qHyDxkTAbTdoWYKnmcoHjQei32Hke2JsCixj3UuIK/NhjoB+3mFs04Z8Tq5GDCAYbxq3L9OiaH0FxO8C1sXabwT3FUScH+VCrVeiH13OO425y3g54YDPKhVEJ4/X1U4jVd9zTtMK3j99hduiy3f6F4cL5mpE3h1YtmGUa/M4uBgaU80j6i9MgSJxU/iFibYD0gxnhTKjfhPBZw/RZTZ7/V2PHwXho0/9W1fHv3KLnri0GHuKbRcSsxMQJPiCwVJ4tEYZXIyZl8/FlSbwba67Z+7vLIWDfHKvxwzAqqK2XZR9qWL+v8WELf2INejPXfFDUFsicFaMO6nplzi850wR3mPi3VOcDllOWLL3hCn3PwQpxqXZ3tMHCYIavAZ8aRUa+T1iKvXjVovgLyJb2AAI7GtHZWzt6PI=

install:
    npm install --global mocha

script:
  - export NS_HOST=$NS_HOST
  - export NS_KEYNAME=$NS_KEYNAME
  - export NS_KEY=$NS_KEY
  - export NS_CPCODE=$NS_CPCODE
  - npm install
  - mocha --no-timeouts test/test-netstorage.js
