language: node_js
node_js:
 - 6.1
 - 6.0
 - 5.11
 - 5.10
 - 5.9
 - 5.8
 - 5.7
 - 5.6
 - 5.5
 - 5.4
 - 5.3
 - 5.2
 - 5.1
 - 5.0
 - 4.4
 - 4.3
 - 4.2
 - 4.1
 - 4.0

env:
  global:
    - secure: GrkVquuYFffXmm+y+PzGl10BygFkRTKhpWigOoZJ+xhO4lrTknGKZt9NI34qYF6Vpb/8kCROyF81rANtjmzOIu77XKoKQPDyKAs+71YqKL5GXwPW3bw7/mQ+regRbPuMVpOJ0i9PBy/YfggJ2ZLKXiKq1wBXbhRE8adjURHgvUMIcZ5zVvR5XM/aWNViZh3ruERss2zH5N4L/9+sf10Qmn7pky/GuOvt++RAjC6Kn6YtuA+2zZP8yBwumj5r9Zz8uzC0sc1OYqJngcOeo4CTQsabeAXWWyzBUJzZjVjCPuca7HNo84cnBUgk7r1N4i57Toq7qwcgxnwNtMejtiMwud4UKGWpfwCyNK++IGiRapJ/ATZAOrbDHx/CXcGaBwaV1OvuC+A7VpPtDou4j/nG/mkWz0cNK6OMzMxa7LkZYfiqEaVzDdh+ONovqkgnDEVkbY6iBGk3NAxECDT/2d1ZQSG5Pbj89t7rLvksIrGiCvo8yic6ktGyYJ7nH3e4kzrQgZY4os1b1yg6G14Bus7vJKGfeKWuG49dY2lrlIJvushY1xAeeyJ7ppcGfy+PGvCoe1KeKsUKGzuPicAxm9NttxQbdV8hJB640iQFtFNs232x1K5dCHfYMYSMe+/aGwnxyhLrAAM2n/4M6bEgt9+Z4gChnQK9/gd0RCB4zL5K/g4=

install:
    npm install --global mocha

script:
  - export NS_KEY=$NS_KEY
  - export NS_KEYNAME=$NS_KEYNAME
  - export NS_HOST=$NS_HOST
  - export NS_CPCODE=$NS_CPCODE
  - mocha --no-timeouts test/test-netstorage.js
